name: Deploy to Dokploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dokploy Webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -d '{"ref":"refs/heads/main"}' \
            "https://dokploy.tallpizza.com/api/deploy/rp62jS1ug6XV3b6QIYG7B"
